import React from 'react';
import { SparkleIcon } from './Icons';

export const MyAppsView = ({ onBackToHome, onOpenApp }) => {
  const sampleApps = [
    {
      id: 'app-1',
      title: 'Study Flow & Timetable',
      category: 'Education',
      description: 'Pomodoro timer with subject allocation and interactive deadline calendar.',
      updatedAt: '2 hours ago',
      color: '#8b5cf6',
      icon: '🎓',
    },
    {
      id: 'app-2',
      title: 'Expense Tracker Pro',
      category: 'Finance',
      description: 'Multi-account financial tracker with monthly budgeting charts.',
      updatedAt: 'Yesterday',
      color: '#10b981',
      icon: '📊',
    },
    {
      id: 'app-3',
      title: 'Habit Hero Streaks',
      category: 'Productivity',
      description: 'Daily habit streaks tracker with visual heatmap calendar.',
      updatedAt: '3 days ago',
      color: '#f43f5e',
      icon: '❤️',
    },
  ];

  return (
    <div className="my-apps-view">
      <div className="my-apps-header">
        <div>
          <h2 className="my-apps-title">My Applications</h2>
          <p className="my-apps-subtitle">All working apps generated by Chameleon in your workspace.</p>
        </div>
        <button type="button" className="btn-primary-small" onClick={onBackToHome}>
          <SparkleIcon size={16} color="#ffffff" />
          <span>New Application</span>
        </button>
      </div>

      <div className="my-apps-grid">
        {sampleApps.map((app) => (
          <div
            key={app.id}
            className="my-app-card"
            onClick={() => onOpenApp && onOpenApp(app)}
          >
            <div className="app-card-top">
              <div className="app-card-icon" style={{ backgroundColor: `${app.color}15` }}>
                <span style={{ fontSize: '20px' }}>{app.icon}</span>
              </div>
              <span className="app-badge" style={{ color: app.color, backgroundColor: `${app.color}18` }}>
                {app.category}
              </span>
            </div>
            <h3 className="app-card-title">{app.title}</h3>
            <p className="app-card-desc">{app.description}</p>
            <div className="app-card-footer">
              <span className="app-updated">{app.updatedAt}</span>
              <span className="app-launch-btn">Open App →</span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default MyAppsView;
