package com.Chameleon.Chameleon.controller;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

@RestController
@RequestMapping({"/api/apps", "/apps"})
@CrossOrigin(origins = "*")
public class AppsController {

    private final Map<String, Map<String, Object>> appsStorage = new ConcurrentHashMap<>();

    public AppsController() {
        // Empty storage by default: only real applications generated by the user are stored!
    }

    private void saveAppInternal(String id, String title, String description, String category, String color, String htmlCode) {
        Map<String, Object> app = new HashMap<>();
        app.put("id", id);
        app.put("title", title);
        app.put("description", description);
        app.put("category", category);
        app.put("color", color);
        app.put("htmlCode", htmlCode);
        app.put("createdAt", LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME));
        app.put("updatedAt", "Just now");
        appsStorage.put(id, app);
    }

    @GetMapping
    public ResponseEntity<List<Map<String, Object>>> listApps() {
        List<Map<String, Object>> list = new ArrayList<>(appsStorage.values());
        return ResponseEntity.ok(list);
    }

    @GetMapping("/{id}")
    public ResponseEntity<?> getApp(@PathVariable String id) {
        Map<String, Object> app = appsStorage.get(id);
        if (app == null) {
            return ResponseEntity.notFound().build();
        }
        return ResponseEntity.ok(app);
    }

    @GetMapping(value = "/{id}/raw", produces = "text/html; charset=UTF-8")
    public ResponseEntity<String> getAppRawHtml(@PathVariable String id) {
        Map<String, Object> app = appsStorage.get(id);
        if (app == null || !app.containsKey("htmlCode")) {
            return ResponseEntity.notFound().build();
        }
        return ResponseEntity.ok((String) app.get("htmlCode"));
    }

    @PostMapping
    public ResponseEntity<Map<String, Object>> saveApp(@RequestBody Map<String, Object> payload) {
        String id = (String) payload.getOrDefault("id", "app-" + UUID.randomUUID().toString().substring(0, 8));
        String title = (String) payload.getOrDefault("title", "Custom Application");
        String description = (String) payload.getOrDefault("description", "AI Generated Application");
        String category = (String) payload.getOrDefault("category", "General");
        String color = (String) payload.getOrDefault("color", "#2563eb");
        String htmlCode = (String) payload.getOrDefault("htmlCode", "");

        saveAppInternal(id, title, description, category, color, htmlCode);
        return ResponseEntity.ok(appsStorage.get(id));
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<Map<String, Object>> deleteApp(@PathVariable String id) {
        Map<String, Object> removed = appsStorage.remove(id);
        if (removed != null) {
            return ResponseEntity.ok(Map.of("success", true, "message", "Application deleted"));
        }
        return ResponseEntity.notFound().build();
    }
}
